version: '3.3'
services:
  db:
    image: mysql:latest
    environment:
      - 'MYSQL_DATABASE='
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER='
    ports:
      - '3306:3306'